{{- $fullName := include "helm-chart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $fullName }}
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ $fullName }}
        # IfNotPresent, Never
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      restartPolicy: Always
