apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.nameOverride }}