apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: predict-flower
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  releaseName: predict-flower
  interval: 1m
  chart:
    spec:
      chart: ./helm-chart
  values:
    image.repository: "acrann.azurecr.io/python-api/predict-flower"
